import type { Product, User, Category } from "./types"

export const categories: Category[] = [
  {
  id: "1",
  name: "Bánh Tráng Muối Nhuyễn",
  price: 25000,
  originalPrice: 30000,
  image: "/products/muoinhuyen.jpg",
  description: "Bánh tráng muối nhuyễn Tây Ninh",
  category: "banh-trang",
  stock: 100,
  unit: "bịch",
  discount: 15,

  shopee: "https://shopee.vn/",
  lazada: "https://www.lazada.vn/",
  tiktok: "https://www.tiktok.com/"
  },
  {
    id: "cat2",
    name: "Muối Chấm",
    image: "/categories/muoicham.jpg",
    slug: "muoi-cham",
  },
  {
    id: "cat3",
    name: "Đồ Ăn Vặt",
    image: "/categories/anvat.jpg",
    slug: "do-an-vat",
  },
  {
    id: "cat4",
    name: "Combo Đặc Sản",
    image: "/categories/combo.jpg",
    slug: "combo-dac-san",
  },
]

export const featuredProducts: Product[] = [
  {
    id: "prod1",
    name: "Bánh Tráng Muối Nhuyễn",
    description: "Bánh tráng Tây Ninh trộn cùng muối nhuyễn đậm đà.",
    price: 35000,
    originalPrice: 45000,
    discount: 22,
    image: "/products/banhtrang-muoinhuyen.jpg",
    category: "banh-trang",
    trending: true,
    bestseller: true,
    stock: 100,
    unit: "bịch",
  },

  {
    id: "prod2",
    name: "Bánh Tráng Tỏi",
    description: "Bánh tráng phơi sương kết hợp tỏi phi thơm ngon.",
    price: 40000,
    originalPrice: 50000,
    discount: 20,
    image: "/products/banhtrang-toi.jpg",
    category: "banh-trang",
    trending: true,
    stock: 80,
    unit: "bịch",
  },

  {
    id: "prod3",
    name: "Bánh Tráng Sa Tế",
    description: "Vị cay nồng hấp dẫn, phù hợp cho tín đồ ăn cay.",
    price: 45000,
    originalPrice: 55000,
    discount: 18,
    image: "/products/banhtrang-sate.jpg",
    category: "banh-trang",
    bestseller: true,
    stock: 70,
    unit: "bịch",
  },

  {
    id: "prod4",
    name: "Muối Tôm Tây Ninh",
    description: "Muối tôm chính gốc Tây Ninh dùng chấm trái cây.",
    price: 25000,
    originalPrice: 30000,
    discount: 17,
    image: "/products/muoitom.jpg",
    category: "muoi-cham",
    stock: 150,
    unit: "hũ",
  },

  {
    id: "prod5",
    name: "Muối Ớt Xanh",
    description: "Muối chấm hải sản và trái cây cực ngon.",
    price: 30000,
    originalPrice: 40000,
    discount: 25,
    image: "/products/muoiotxanh.jpg",
    category: "muoi-cham",
    stock: 90,
    unit: "hũ",
  },

  {
    id: "prod6",
    name: "Khô Gà Lá Chanh",
    description: "Khô gà cay nhẹ, thơm mùi lá chanh.",
    price: 65000,
    originalPrice: 80000,
    discount: 19,
    image: "/products/khoga.jpg",
    category: "do-an-vat",
    new: true,
    stock: 60,
    unit: "hộp",
  },

  {
    id: "prod7",
    name: "Combo Đặc Sản Tây Ninh",
    description: "Combo bánh tráng, muối tôm và đồ ăn vặt.",
    price: 149000,
    originalPrice: 179000,
    discount: 17,
    image: "/products/combo-tayninh.jpg",
    category: "combo-dac-san",
    trending: true,
    bestseller: true,
    stock: 30,
    unit: "combo",
  },

  {
    id: "prod8",
    name: "Bánh Tráng Phơi Sương",
    description: "Đặc sản nổi tiếng Tây Ninh, mềm dẻo tự nhiên.",
    price: 55000,
    originalPrice: 65000,
    discount: 15,
    image: "/products/phoisuong.jpg",
    category: "banh-trang",
    new: true,
    stock: 50,
    unit: "bịch",
  },
]